development:
  adapter: postgresql
  encoding: unicode
  database: gps-api_dev
  pool: 5
  username: mark
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: gps-api_test
  pool: 5
  username: mark
  password: 